scrive/scrive-apidocs

documentation/api/documents/document_id/forward.yaml
documentation/scrive_api.yaml

Plan to go live on 2016-12-17
Case 2352.

Extra 'no_attachments' parameter to 'forward' API call

---

documentation/api/documents/document_id/signatory_id/highlight.yaml
documentation/definitions/Document.yaml
documentation/definitions/Signatory.yaml
documentation/scrive_api.yaml

See [Case 2538](https://scrive.fogbugz.com/f/cases/2538).
If everything looks good, can you merge?
Everything described in this PR is already on `production` and can just be merged straight away.

Documentation for 'allows_highlighting', 'highlighted_pages', and 'document_is_receipt'

---

documentation/api/documents/document_id/removepages.yaml
documentation/scrive_api.yaml

Added documentation for removepages

---

documentation/api/documents/short_document_id/getbyshortid.yaml
documentation/scrive_api.yaml

_To be merged after production update on 25th February_
New API Call in progress.
See Case 2624.

Add documentation for getbyshortid

---

documentation/scrive_api.yaml

s/electronic signature/digital signature
Case 2663

Minor re-wording of digital signature

---

documentation/api/documents/document_id/signatory_id/setauthenticationtoview.yaml
documentation/definitions/Signatory.yaml
documentation/scrive_api.yaml

Please review.
Should be merged anytime _after_ production update on Sat 11th March.

Add 'dk_nemid' (Danish NemId) to 'authentication_to_view'

---

documentation/scrive_user_api.yaml

I am not sure, how/whether to document /loginwithredirect. That one is not part of API, it is used by the end user only.

Document loginandgetsession User API call

---

documentation/definitions/ListFilter.yaml

Also add a small description of the filters.
We could add more detail in the future...
Case 2881.

Clarify implcity filter added by is_signable_on_pad

---

documentation/definitions/SignatoryFieldStandard.yaml
documentation/scrive_api.yaml

@Paczesiowa could you review? I need a positive review to be able to merge this...

Add missing 'company' to enum of standard signatory field

---

documentation/scrive_api.yaml

@mariuszrak could you please review and merge? Thanks.

Remove incorrect statement about anchoring when upgrading from V1

---

documentation/api/documents/list.yaml

We will merge when deployment to production is done.

Fix error in list call sorting default

---

documentation/api/documents/document_id/files/main.yaml

Add description of "get main file" HTTP 503 error case

---

documentation/api/documents/document_id/setfile.yaml

Case 3293.
@mariuszrak could you please approve and merge (subject to build not failing).

Add a small note about anchors to setfile description

---

documentation/scrive_api.yaml

Case 2972.
@mariuszrak could you please approve and merge (subject to build not failing).
For reference, this is what it looks like:

Add a note about supported encoding.

---

documentation/api/documents/document_id/setattachments.yaml
documentation/api/documents/document_id/update.yaml
documentation/api/documents/list.yaml
documentation/definitions/SignatoryFieldCustomText.yaml
documentation/definitions/SignatoryFieldCustomValidation.yaml
documentation/scrive_api.yaml

[Case 3507](https://scrive.fogbugz.com/f/cases/3507/Add-custom-validation-to-API-Documentation).

Document custom validations.

---

documentation/scrive_api.yaml

Update production IP address list

---

documentation/api/documents/document_id/signatory_id/getqrcode.yaml
documentation/extras/responses.yaml
documentation/scrive_api.yaml

Document the getqrcode API call.

---

documentation/api/documents/document_id/signatory_id/changeemailandmobile.yaml
documentation/scrive_api.yaml

Just a review
Case 3681
1. This endpoint needs to be released to production first
2. I need to add it to the `CHANGELOG`, but I'm not yet sure when this will be released

Document changeemailandmobile endpoint

---

documentation/definitions/Signatory.yaml

**Do not merge before Monday 29th.**

Add hide_personal_number_in_evidence_log to Document

---

documentation/api/documents/document_id/signatory_id/setauthenticationtosign.yaml

Fix parameters for setauthenticationtosign

---

documentation/definitions/Signatory.yaml
documentation/definitions/SignatoryConsentModule.yaml

The implementation PR is here: https://github.com/scrive/kontrakcja/pull/774

CORE-10 - Add consent_module to signatory JSON

---

documentation/definitions/Signatory.yaml

Clarify API / Link delivery method

---

documentation/api/documents/document_id/signatory_id/setauthenticationtosign.yaml
documentation/definitions/Signatory.yaml
documentation/extras/parameters.yaml
documentation/scrive_api.yaml

CORE-675
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scrive/scrive-apidocs/40)

Add dk_nemid as authentication_to_sign

---

documentation/api/attachments/delete.yaml
documentation/api/attachments/download.yaml
documentation/api/attachments/list.yaml
documentation/api/attachments/new.yaml
documentation/api/attachments/setsharing.yaml
documentation/api/documents/document_id/files/file_id.yaml
documentation/api/documents/document_id/files/main.yaml
documentation/definitions/Attachment.yaml
documentation/definitions/AttachmentListFilter.yaml
documentation/scrive_api.yaml

https://github.com/scrive/kontrakcja/pull/891
https://scriveab.atlassian.net/browse/CORE-588
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scrive/scrive-apidocs/41)

CORE-588 - Attachment API

---

documentation/api/documents/document_id/signatory_id/approve.yaml
documentation/api/documents/document_id/signatory_id/reject.yaml
documentation/definitions/Document.yaml
documentation/definitions/Signatory.yaml
documentation/definitions/SignatoryRole.yaml
documentation/scrive_api.yaml

[CORE-187](https://scriveab.atlassian.net/browse/CORE-187).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scrive/scrive-apidocs/39)

Documentation for 'signatory_role' and the 'approve' call

---

documentation/scrive_api.yaml

This PR fixes the lack of change log row additions in PR #43.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scrive/scrive-apidocs/44)

Add missing change log rows

---

documentation/api/user/2fa-confirm.yaml
documentation/api/user/2fa-disable.yaml
documentation/api/user/2fa-setup.yaml
documentation/api/user/deleteuser.yaml
documentation/api/user/get-dataretentionpolicy.yaml
documentation/api/user/isuserdeletable.yaml
documentation/api/user/loginandgetsession.yaml
documentation/api/user/post-dataretentionpolicy.yaml
documentation/definitions/DataRetentionPolicies.yaml
documentation/definitions/DataRetentionPolicy.yaml
documentation/definitions/OAuthAuthorization.yaml
documentation/scrive_api.yaml

- loginandgetsession oauth endpoint
- 2fa endpoints
- delete user endpoints
- dataretentionpolicy endpoints
(.. and many more are still missing)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scrive/scrive-apidocs/46)

Add missing UserAPI endpoints documentation

---

documentation/api/monitor/status.yaml
documentation/scrive_api.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scrive/scrive-apidocs/50)

Add monitoring status endpoint

---

documentation/scrive_api.yaml

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scrive/scrive-apidocs/51)

Clarify that user callbacks are secondary and not preferred

---

documentation/definitions/Signatory.yaml

https://scriveab.atlassian.net/browse/CORE-1338
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scrive/scrive-apidocs/52)

CORE-1338 - add sms_pin to ATV and ATVA documentation

---

documentation/scrive_api.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scrive/scrive-apidocs/57)

re-ordered changelog; added two previous changes.

---

documentation/definitions/Signatory.yaml
documentation/scrive_api.yaml

Customers asked about how to use link confirmation delivery. I also added more words to explain the options.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scrive/scrive-apidocs/59)

Added documentation for new confirmation delivery options.

---

documentation/api/user/loginandgetsession.yaml
documentation/api/user/signup.yaml
documentation/scrive_api.yaml

Also take better description for loginandgetsession endpoint from that
branch
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scrive/scrive-apidocs/49)

Add /signup endpoint from dev-user-api branch

---

documentation/api/usergroup/createusergroup.yaml
documentation/api/usergroup/deleteusergroup.yaml
documentation/api/usergroup/deleteusergroupcontactdetails.yaml
documentation/api/usergroup/deleteusergroupsettings.yaml
documentation/api/usergroup/getusergroup.yaml
documentation/api/usergroup/getusergroupcontactdetails.yaml
documentation/api/usergroup/getusergroupsettings.yaml
documentation/api/usergroup/updateusergroup.yaml
documentation/api/usergroup/updateusergroupcontactdetails.yaml
documentation/api/usergroup/updateusergroupsettings.yaml
documentation/definitions/UserGroup.yaml
documentation/definitions/UserGroupContactDetails.yaml
documentation/definitions/UserGroupContactDetailsWithInheritable.yaml
documentation/definitions/UserGroupSettings.yaml
documentation/definitions/UserGroupSettingsWithInheritable.yaml
documentation/definitions/UserGroupWithInheritable.yaml
documentation/extras/responses.yaml
documentation/scrive_api.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scrive/scrive-apidocs/60)

CORE-978 User Group API Documentation

---

documentation/api/usergroup/createusergroup.yaml
documentation/api/usergroup/deleteusergroup.yaml
documentation/api/usergroup/deleteusergroupcontactdetails.yaml
documentation/api/usergroup/deleteusergroupsettings.yaml
documentation/api/usergroup/getusergroup.yaml
documentation/api/usergroup/getusergroupcontactdetails.yaml
documentation/api/usergroup/getusergroupsettings.yaml
documentation/api/usergroup/updateusergroup.yaml
documentation/api/usergroup/updateusergroupcontactdetails.yaml
documentation/api/usergroup/updateusergroupsettings.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scrive/scrive-apidocs/66)

CORE-978 Fix include-inheritable flag typo

---

Gemfile
Gemfile.lock

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scrive/scrive-apidocs/67)

Fix dependency alerts

---

documentation/definitions/Signatory.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scrive/scrive-apidocs/65)

clarify "pad" delivery method

---

documentation/definitions/Document.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scrive/scrive-apidocs/68)

Add documentation about show-arrow option

---

documentation/api/usergroup/createusergroup.yaml
documentation/api/usergroup/deleteusergroupcontactdetails.yaml
documentation/api/usergroup/deleteusergroupsettings.yaml
documentation/api/usergroup/getusergroup.yaml
documentation/api/usergroup/getusergroupcontactdetails.yaml
documentation/api/usergroup/getusergroupsettings.yaml
documentation/api/usergroup/updateusergroup.yaml
documentation/api/usergroup/updateusergroupcontactdetails.yaml
documentation/api/usergroup/updateusergroupsettings.yaml
documentation/definitions/UserGroup.yaml
documentation/definitions/UserGroupContactDetails.yaml
documentation/definitions/UserGroupContactDetailsWithInheritable.yaml
documentation/definitions/UserGroupSettings.yaml
documentation/definitions/UserGroupSettingsWithInheritable.yaml
documentation/definitions/UserGroupWithInheritable.yaml
documentation/scrive_api.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scrive/scrive-apidocs/69)

Updated Documentation for User Group API

---

documentation/api/usergroup/deleteusergroupcontactdetails.yaml
documentation/api/usergroup/deleteusergroupsettings.yaml
documentation/api/usergroup/updateusergroup.yaml
documentation/api/usergroup/updateusergroupcontactdetails.yaml
documentation/api/usergroup/updateusergroupsettings.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scrive/scrive-apidocs/70)

Updated "include-inheritable" Parameters

---

Gemfile.lock
documentation/api/accesscontrol/createrole.yaml
documentation/api/accesscontrol/deleterole.yaml
documentation/api/accesscontrol/getrole.yaml
documentation/api/accesscontrol/getuserroles.yaml
documentation/api/usergroup/deleteusergroup.yaml
documentation/definitions/AccessRole.yaml
documentation/scrive_api.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scrive/scrive-apidocs/64)

CORE-980 Access Control Documentation

---

documentation/api/documents/document_id/signatory_id/setauthenticationtoview.yaml
documentation/definitions/Signatory.yaml
documentation/scrive_api.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scrive/scrive-apidocs/71)

Add verimi to authToView

---

documentation/scrive_api.yaml

@Paczesiowa or @piotrskowron-scrive can you confirm that this IP list looks correct now?
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scrive/scrive-apidocs/75)

Update production IP addresses

---

documentation/api/accesscontrol/createrole.yaml
documentation/api/accesscontrol/getrole.yaml
documentation/api/folders/createfolder.yaml
documentation/api/folders/deletefolder.yaml
documentation/api/folders/getfolder.yaml
documentation/api/folders/listdocuments.yaml
documentation/api/folders/updatefolder.yaml
documentation/definitions/Folder.yaml
documentation/scrive_api.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scrive/scrive-apidocs/74)

CORE-1674 Folders API documentation

---

documentation/scrive_api.yaml

I winged some dates based on commit messages and put them in the version history table. Should be accurate enough-ish.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scrive/scrive-apidocs/76)

Added version history for access control, user, user group, folder APIs.

---

documentation/api/documents/short_document_id/getbyshortid.yaml
documentation/scrive_api.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scrive/scrive-apidocs/79)

Change getbyshortid conditions (72h from created time)

---

documentation/api/usergroup/listusersinusergroup.yaml
documentation/definitions/User.yaml
documentation/scrive_api.yaml

[CORE-1845](https://scriveab.atlassian.net/browse/CORE-1845)
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scrive/scrive-apidocs/80)

CORE-1845 Add User Group /users listing endpoint to docs

---

documentation/api/user/get-tags.yaml
documentation/api/user/post-tags.yaml
documentation/definitions/Tags.yaml
documentation/scrive_api.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scrive/scrive-apidocs/83)

CORE-1840 user tags api

---

documentation/definitions/SignatoryFieldStandardPlacements.yaml

The use of the word "width" is ambiguous in this context.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scrive/scrive-apidocs/81)

change 'width' to 'height'

---

documentation/api/user/get-tags.yaml
documentation/api/user/post-tags.yaml
documentation/definitions/Tags.yaml
documentation/scrive_api.yaml

This has already been reviewed and merged in https://github.com/scrive/scrive-apidocs/pull/83 but there was a mix-up with the target branch.
Please merge again into master.
@trin-cz @jonathanjouty
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scrive/scrive-apidocs/86)

CORE-1840 user tags api, take #2

---

documentation/definitions/Signatory.yaml
documentation/scrive_api.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scrive/scrive-apidocs/87)

Add missing authentication methods.

---

source/404.html

Adapted from https://github.com/csuwildcat/sghpa
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scrive/scrive-apidocs/88)

Try adding a 404 that redirects to '/'

---

documentation/scrive_api.yaml

https://scriveab.atlassian.net/browse/DEVOPS-215
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scrive/scrive-apidocs/91)

DEVOPS-215: New IP Address

---

documentation/api/documents/document_id/signatory_id/setauthenticationtosign.yaml
documentation/definitions/Signatory.yaml
documentation/extras/parameters.yaml
documentation/scrive_api.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scrive/scrive-apidocs/92)

Add Onfido authentication to sign methods

---

documentation/api/documents/list.yaml

https://scriveab.atlassian.net/browse/CORE-2306
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scrive/scrive-apidocs/95)

Add document list call instructions

---

documentation/scrive_api.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scrive/scrive-apidocs/96)

added two missing ip-addresses to list of endpoints

---

documentation/scrive_api.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scrive/scrive-apidocs/97)

Change contact email to support at scrive.com

---

documentation/api/attachments/delete.yaml
documentation/api/attachments/download.yaml
documentation/api/attachments/list.yaml
documentation/api/attachments/new.yaml
documentation/api/attachments/setsharing.yaml
documentation/api/folders/createfolder.yaml
documentation/api/folders/deletefolder.yaml
documentation/api/folders/getfolder.yaml
documentation/api/folders/listdocuments.yaml
documentation/api/user/loginandgetsession.yaml
documentation/api/usergroup/createusergroup.yaml
documentation/api/usergroup/deleteusergroup.yaml
documentation/api/usergroup/deleteusergroupcontactdetails.yaml
documentation/api/usergroup/deleteusergroupsettings.yaml
documentation/api/usergroup/getusergroup.yaml
documentation/api/usergroup/getusergroupcontactdetails.yaml
documentation/api/usergroup/getusergroupsettings.yaml
documentation/api/usergroup/listusersinusergroup.yaml
documentation/api/usergroup/updateusergroup.yaml
documentation/api/usergroup/updateusergroupcontactdetails.yaml
documentation/api/usergroup/updateusergroupsettings.yaml
documentation/scrive_api.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scrive/scrive-apidocs/99)

CORE-2548 Document `FULL_ACCESS` privilege

---

documentation/scrive_api.yaml

Comments from both Axel and Patrick about stray quotes and non-standard names.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scrive/scrive-apidocs/98)

Prettified changelog a bit.

---

documentation/api/documents/document_id/signatory_id/setauthenticationtosign.yaml
documentation/api/documents/document_id/signatory_id/setauthenticationtoview.yaml
documentation/definitions/Signatory.yaml
documentation/extras/parameters.yaml
documentation/scrive_api.yaml

https://scriveab.atlassian.net/browse/CORE-2610
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scrive/scrive-apidocs/100)

CORE-2610: Update apidocs.scrive.com, adding NemID authentication methods

---

documentation/definitions/ListFilter.yaml

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/scrive/scrive-apidocs/102)

FLOW-283 Allow filtering flow docs in list calls
